version: "1.1"

services:
  db:
    image: postgres
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=school
